name: Checking and Formatting

on:
  push:
    branches: [main]

jobs:
  check:
    name: Astro Check & Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Astro Check
        run: pnpm astro check

      - name: Prettier Format Check
        run: pnpm format:check
